name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Path to test file'
        required: false
        default: 'tests/calculator.spec.js'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TEST_FILE: ${{ github.event.inputs.test_file || 'tests/calculator.spec.js'}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: xvfb-run -a npx playwright test "$TEST_FILE"


